### ISSUE TITLE
If an author doesn't have a profile picture, show placeholder image

### ISSUE THREAD

**Issue by n-young** [CaoRuiming/bpr-wordpress#59]
![Screenshot from 2021-02-22 19-18-03](https://user-images.githubusercontent.com/2057596/108786968-c64a9500-7542-11eb-95a1-f9623359b32f.png)
![Screenshot from 2021-02-22 19-18-18](https://user-images.githubusercontent.com/2057596/108786969-c64a9500-7542-11eb-8b29-1302c17da6fa.png)

**Comment by n-young** [comment]
Look at [this pr](https://github.com/CaoRuiming/bpr-wordpress/pull/31) for an idea of which files you need to fix. Specifically, in the `wp-content/themes/bpr2018/resources/templates/author.tpl.php` file, add a `<? php if (cond)>` field to ensure that lines 5 through 7 are only displayed in the case that there is actually a profile picture to be displayed

**Comment by CaoRuiming** [comment]
Because there is no easy way to tell if the author does not have a profile picture, let's display a placeholder image instead (look at how placeholder images are handled for articles on the front page). This should work since authors who don't have profile pictures will have completely transparent images instead.
